In [1]:
import pandas as pd
import os
from nba_api.stats.static import players,teams

nba_teams = teams.get_teams()
teamids= {}
team_acr = {}
team_ids = {
    'SEA': 1610612760,  # Seattle SuperSonics
    'CHH': 1610612766,  # Charlotte Hornets (original)
    'NJN': 1610612751,  # New Jersey Nets
    'NOH': 1610612740   # New Orleans Hornets (now New Orleans Pelicans)
}
team_extra={'1610612760': 'SEA', '1610612766': 'CHH', '1610612751': 'NJN', '1610612740': 'NOH'}

team_acr.update(team_ids)

teamids.update(team_extra)
opp_frames=[]
for org in nba_teams:
    teamids[str(org['id'])]=org['abbreviation']
    team_acr[org['abbreviation']] = str(org['id'])
for year in range(1997,2025):
    dir_path='team/'+str(year)+'ps/'
    csvs= os.listdir(dir_path)
    csvs =[csv for csv in csvs if '.csv' in csv]

    csvs =[csv for csv in csvs if 'vs' not in csv]
    csvs =[csv for csv in csvs if 'avg' not in csv]
    print(csvs)
    for csv in csvs:
        file_path = dir_path+csv
        team_id = csv.split('.')[0]

        df = pd.read_csv(file_path)
        df=df.sort_values(by='SHOT_ID')
        df=df[['VTM']]
        
        df =df.drop_duplicates()
        

        team_ac = teamids[team_id]
        #print(team_ac)
        df=df[df.VTM!=team_ac]
        df.columns=['OPP']

        df['OPP_ID']=df['OPP'].map(team_acr)
        df['OPP_ID'] = df['OPP_ID'].astype(str)
        df['TEAM_ID']= int(team_id)
        df['TEAM']= team_ac
        df['Round'] = [i+1 for i in range(0,len(df))]
        df['year']=year
        opp_frames.append(df)

opp_matchups = pd.concat(opp_frames)
opp_matchups.to_csv('opponentmatch.csv',index=False)
opp_matchups

['1610612756.csv', '1610612765.csv', '1610612757.csv', '1610612747.csv', '1610612753.csv', '1610612766.csv', '1610612746.csv', '1610612764.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612762.csv', '1610612752.csv', '1610612741.csv', '1610612750.csv', '1610612745.csv']
['1610612756.csv', '1610612757.csv', '1610612747.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612762.csv', '1610612752.csv', '1610612741.csv', '1610612750.csv', '1610612751.csv', '1610612739.csv', '1610612745.csv']
['1610612756.csv', '1610612765.csv', '1610612757.csv', '1610612749.csv', '1610612747.csv', '1610612753.csv', '1610612754.csv', '1610612759.csv', '1610612748.csv', '1610612737.csv', '1610612762.csv', '1610612752.csv', '1610612750.csv', '1610612745.csv', '1610612758.csv', '1610612755.csv']
['1610612756.csv', '1610612765.csv', '1610612757.csv', '1610612749.csv', '1610612747.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612748.csv', '1610612760.csv', '1610612762.csv', '1610612752.csv', '1610612750.csv', '1610612758.csv', '1610612761.csv', '1610612755.csv']
['1610612756.csv', '1610612757.csv', '1610612749.csv', '1610612747.csv', '1610612753.csv', '1610612742.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612748.csv', '1610612762.csv', '1610612752.csv', '1610612750.csv', '1610612758.csv', '1610612761.csv', '1610612755.csv']
['1610612765.csv', '1610612757.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612742.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612760.csv', '1610612762.csv', '1610612750.csv', '1610612751.csv', '1610612758.csv', '1610612761.csv', '1610612755.csv']
['1610612756.csv', '1610612765.csv', '1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612740.csv', '1610612742.csv', '1610612754.csv', '1610612759.csv', '1610612762.csv', '1610612750.csv', '1610612751.csv', '1610612758.csv', '1610612755.csv']
['1610612765.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612740.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612763.csv', '1610612748.csv', '1610612752.csv', '1610612750.csv', '1610612751.csv', '1610612745.csv', '1610612758.csv']
['1610612756.csv', '1610612765.csv', '1610612738.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612763.csv', '1610612764.csv', '1610612748.csv', '1610612760.csv', '1610612741.csv', '1610612751.csv', '1610612745.csv', '1610612758.csv', '1610612755.csv']
['1610612756.csv', '1610612765.csv', '1610612749.csv', '1610612747.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612764.csv', '1610612748.csv', '1610612741.csv', '1610612751.csv', '1610612739.csv', '1610612758.csv']
['1610612756.csv', '1610612765.csv', '1610612747.csv', '1610612753.csv', '1610612742.csv', '1610612743.csv', '1610612759.csv', '1610612764.csv', '1610612748.csv', '1610612762.csv', '1610612741.csv', '1610612751.csv', '1610612739.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv']
['1610612756.csv', '1610612765.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612740.csv', '1610612742.csv', '1610612743.csv', '1610612759.csv', '1610612764.csv', '1610612737.csv', '1610612762.csv', '1610612739.csv', '1610612745.csv', '1610612761.csv', '1610612755.csv']
['1610612765.csv', '1610612757.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612740.csv', '1610612742.csv', '1610612743.csv', '1610612759.csv', '1610612748.csv', '1610612737.csv', '1610612762.csv', '1610612741.csv', '1610612739.csv', '1610612745.csv', '1610612755.csv']
['1610612756.csv', '1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612742.csv', '1610612743.csv', '1610612766.csv', '1610612759.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612762.csv', '1610612741.csv', '1610612739.csv']
['1610612757.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612740.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612763.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612752.csv', '1610612741.csv', '1610612755.csv']
['1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612762.csv', '1610612752.csv', '1610612741.csv', '1610612755.csv']
['1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612752.csv', '1610612741.csv', '1610612751.csv', '1610612745.csv', '1610612744.csv']
['1610612757.csv', '1610612742.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612764.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612741.csv', '1610612751.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv']
['1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612740.csv', '1610612742.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612764.csv', '1610612737.csv', '1610612741.csv', '1610612751.csv', '1610612739.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv']
['1610612765.csv', '1610612757.csv', '1610612738.csv', '1610612742.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612739.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv']
['1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612754.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612764.csv', '1610612737.csv', '1610612760.csv', '1610612762.csv', '1610612741.csv', '1610612739.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv']
['1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612740.csv', '1610612754.csv', '1610612759.csv', '1610612764.csv', '1610612748.csv', '1610612760.csv', '1610612762.csv', '1610612750.csv', '1610612739.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv', '1610612755.csv']
['1610612765.csv', '1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612753.csv', '1610612743.csv', '1610612754.csv', '1610612759.csv', '1610612746.csv', '1610612760.csv', '1610612762.csv', '1610612751.csv', '1610612745.csv', '1610612744.csv', '1610612761.csv', '1610612755.csv']
['1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612746.csv', '1610612748.csv', '1610612760.csv', '1610612762.csv', '1610612751.csv', '1610612745.csv', '1610612761.csv', '1610612755.csv']
['1610612756.csv', '1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612742.csv', '1610612743.csv', '1610612746.csv', '1610612763.csv', '1610612764.csv', '1610612748.csv', '1610612737.csv', '1610612762.csv', '1610612752.csv', '1610612751.csv', '1610612755.csv']
['1610612756.csv', '1610612749.csv', '1610612738.csv', '1610612740.csv', '1610612742.csv', '1610612743.csv', '1610612763.csv', '1610612748.csv', '1610612737.csv', '1610612762.csv', '1610612741.csv', '1610612750.csv', '1610612751.csv', '1610612744.csv', '1610612761.csv', '1610612755.csv']
['1610612756.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612743.csv', '1610612746.csv', '1610612763.csv', '1610612748.csv', '1610612737.csv', '1610612752.csv', '1610612750.csv', '1610612751.csv', '1610612739.csv', '1610612744.csv', '1610612758.csv', '1610612755.csv']
['1610612756.csv', '1610612765.csv', '1610612757.csv', '1610612749.csv', '1610612738.csv', '1610612747.csv', '1610612753.csv', '1610612740.csv', '1610612742.csv', '1610612743.csv', '1610612754.csv', '1610612766.csv', '1610612759.csv', '1610612746.csv', '1610612763.csv', '1610612764.csv', '1610612748.csv', '1610612737.csv', '1610612760.csv', '1610612762.csv', '1610612752.csv', '1610612741.csv', '1610612750.csv', '1610612751.csv', '1610612739.csv', '1610612745.csv', '1610612744.csv', '1610612758.csv', '1610612761.csv', '1610612755.csv']

     OPP      OPP_ID     TEAM_ID TEAM  Round  year
150  SEA  1610612760  1610612756  PHX    1.0  1997
145  ATL  1610612737  1610612765  DET    1.0  1997
148  LAL  1610612747  1610612757  POR    1.0  1997
0    POR  1610612757  1610612747  LAL    1.0  1997
430  UTA  1610612762  1610612747  LAL    2.0  1997
..   ...         ...         ...  ...    ...   ...
579  DEN  1610612743  1610612750  MIN    2.0  2024
904  DAL  1610612742  1610612750  MIN    3.0  2024
0    ORL  1610612753  1610612739  CLE    1.0  2024
744  BOS  1610612738  1610612739  CLE    2.0  2024
165  NYK  1610612752  1610612755  PHI    1.0  2024

[862 rows x 6 columns]

In [2]:
team_ids = {
    'SEA': 1610612760,
    'CHH': 1610612766,
    'NJN': 1610612751,
    'NOH': 1610612740
}

# Reverse the dictionary
reversed_team_ids = {v: k for k, v in team_ids.items()}

print(reversed_team_ids)

{1610612760: 'SEA', 1610612766: 'CHH', 1610612751: 'NJN', 1610612740: 'NOH'}

In [3]:
opp_matchups[opp_matchups.TEAM=='BOS']

      OPP      OPP_ID     TEAM_ID TEAM  Round  year
0     PHI  1610612755  1610612738  BOS    1.0  2002
541   DET  1610612765  1610612738  BOS    2.0  2002
939   NJN  1610612751  1610612738  BOS    3.0  2002
156   IND  1610612754  1610612738  BOS    1.0  2003
623   NJN  1610612751  1610612738  BOS    2.0  2003
139   IND  1610612754  1610612738  BOS    1.0  2004
0     IND  1610612754  1610612738  BOS    1.0  2005
0     ATL  1610612737  1610612738  BOS    1.0  2008
572   CLE  1610612739  1610612738  BOS    2.0  2008
1068  DET  1610612765  1610612738  BOS    3.0  2008
1489  LAL  1610612747  1610612738  BOS    4.0  2008
0     CHI  1610612741  1610612738  BOS    1.0  2009
639   ORL  1610612753  1610612738  BOS    2.0  2009
0     MIA  1610612748  1610612738  BOS    1.0  2010
524   CLE  1610612739  1610612738  BOS    2.0  2010
987   ORL  1610612753  1610612738  BOS    3.0  2010
1434  LAL  1610612747  1610612738  BOS    4.0  2010
0     NYK  1610612752  1610612738  BOS    1.0  2011
481   MIA  1610612748  1610612738  BOS    2.0  2011
150   ATL  1610612737  1610612738  BOS    1.0  2012
460   PHI  1610612755  1610612738  BOS    2.0  2012
1151  MIA  1610612748  1610612738  BOS    3.0  2012
135   NYK  1610612752  1610612738  BOS    1.0  2013
164   CLE  1610612739  1610612738  BOS    1.0  2015
190   ATL  1610612737  1610612738  BOS    1.0  2016
0     CHI  1610612741  1610612738  BOS    1.0  2017
504   WAS  1610612764  1610612738  BOS    2.0  2017
1083  CLE  1610612739  1610612738  BOS    3.0  2017
0     MIL  1610612749  1610612738  BOS    1.0  2018
670   PHI  1610612755  1610612738  BOS    2.0  2018
1003  CLE  1610612739  1610612738  BOS    3.0  2018
0     IND  1610612754  1610612738  BOS    1.0  2019
493   MIL  1610612749  1610612738  BOS    2.0  2019
0     PHI  1610612755  1610612738  BOS    1.0  2020
925   MIA  1610612748  1610612738  BOS    2.0  2020
504   TOR  1610612761  1610612738  BOS    3.0  2020
176   BKN  1610612751  1610612738  BOS    1.0  2021
337   MIL  1610612749  1610612738  BOS    1.0  2022
1092  MIA  1610612748  1610612738  BOS    2.0  2022
1633  GSW  1610612744  1610612738  BOS    3.0  2022
0     BKN  1610612751  1610612738  BOS    4.0  2022
0     ATL  1610612737  1610612738  BOS    1.0  2023
541   PHI  1610612755  1610612738  BOS    2.0  2023
1129  MIA  1610612748  1610612738  BOS    3.0  2023
0     MIA  1610612748  1610612738  BOS    1.0  2024
407   CLE  1610612739  1610612738  BOS    2.0  2024
817   IND  1610612754  1610612738  BOS    3.0  2024
1176  DAL  1610612742  1610612738  BOS    4.0  2024